logging:
   file:
      name: logs/application.log
spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/notification?useSSL=false&serverTimezone=UTC
      username: root
      password: 1234
   jpa:
      hibernate:
         ddl-auto: update
      generate-ddl: true
      show-sql: true
      properties:
         hibernate:
            generate_statistics: true
   jackson:
      serialization:
         fail-on-empty-beans: false
security:
   jwt:
      token:
         secret-key: secret
      expire-length: 3600000
server:
   port: 8085
   session-timeout: 30
app:
    firebase-configuration-file: fcm/spring-boot-with-fcm-firebase-adminsdk-yu5ad-c866bbab0a.json